export type Product = {
  id: string;
  name: string;
  category: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviews: number;
  description: string;
  specs: Record<string, string>;
  image: string;
  inStock: boolean;
  featured?: boolean;
};

export const PRODUCTS: Product[] = [
  {
    id: "rtx-4090",
    name: "RTX 4090 Graphics Card",
    category: "GPUs",
    price: 1599,
    originalPrice: 1799,
    rating: 4.9,
    reviews: 428,
    description: "Ultimate gaming and content creation GPU with 24GB GDDR6X memory",
    specs: {
      Memory: "24GB GDDR6X",
      Interface: "PCIe 4.0",
      Power: "575W",
      Architecture: "Ada Lovelace",
    },
    image: "/products/gpu.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "ryzen-9-7950x",
    name: "AMD Ryzen 9 7950X",
    category: "CPUs",
    price: 699,
    originalPrice: 799,
    rating: 4.8,
    reviews: 312,
    description: "High-end 16-core processor for gaming and professional workloads",
    specs: {
      Cores: "16 cores / 32 threads",
      "Base Clock": "4.5 GHz",
      "Boost Clock": "5.7 GHz",
      TDP: "162W",
    },
    image: "/products/cpu.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "ddr5-64gb",
    name: "DDR5 64GB Kit (32x2)",
    category: "Memory",
    price: 359,
    rating: 4.7,
    reviews: 256,
    description: "High-speed DDR5 memory kit optimized for gaming and productivity",
    specs: {
      Capacity: "64GB (32GB x 2)",
      Speed: "6000 MHz",
      Latency: "CAS 30",
      Voltage: "1.40V",
    },
    image: "/products/ram.jpg",
    inStock: true,
  },
  {
    id: "nvme-4tb",
    name: "Samsung 990 Pro 4TB NVMe",
    category: "Storage",
    price: 429,
    originalPrice: 499,
    rating: 4.9,
    reviews: 189,
    description: "PCIe 4.0 NVMe SSD with ultra-fast sequential speeds",
    specs: {
      Capacity: "4TB",
      Interface: "PCIe 4.0",
      "Read Speed": "7,100 MB/s",
      "Write Speed": "6,000 MB/s",
    },
    image: "/products/ssd.jpg",
    inStock: true,
    featured: true,
  },
  {
    id: "evga-1200w",
    name: "EVGA SuperNOVA 1200W Platinum",
    category: "Power Supplies",
    price: 299,
    originalPrice: 349,
    rating: 4.8,
    reviews: 224,
    description: "Fully modular 1200W platinum-rated power supply",
    specs: {
      Wattage: "1200W",
      Efficiency: "92%+",
      Modular: "Fully Modular",
      Certification: "80+ Platinum",
    },
    image: "/products/psu.jpg",
    inStock: true,
  },
  {
    id: "corsair-h150i",
    name: "Corsair H150i Elite Capellix",
    category: "Cooling",
    price: 189,
    rating: 4.7,
    reviews: 178,
    description: "360mm all-in-one liquid cooler with RGB lighting",
    specs: {
      Type: "AIO Liquid Cooler",
      Radiator: "360mm",
      Pump: "50 CFM",
      "Noise Level": "37 dB",
    },
    image: "/products/cooler.jpg",
    inStock: true,
  },
  {
    id: "z790-motherboard",
    name: "ASUS ROG MAXIMUS Z790",
    category: "Motherboards",
    price: 459,
    originalPrice: 549,
    rating: 4.8,
    reviews: 142,
    description: "Premium Z790 motherboard with WiFi 6E and Thunderbolt 4",
    specs: {
      Socket: "LGA1700",
      Chipset: "Intel Z790",
      "RAM Slots": "4x DDR5",
      "Expansion Slots": "3x PCIe 5.0",
    },
    image: "/products/mobo.jpg",
    inStock: true,
  },
  {
    id: "lian-li-case",
    name: "Lian Li Lancool 305M Case",
    category: "Cases",
    price: 129,
    rating: 4.6,
    reviews: 156,
    description: "Compact mid-tower case with excellent airflow",
    specs: {
      Dimensions: "430 x 200 x 430mm",
      "Max GPU Length": "320mm",
      "Front Fans": "3x 120mm",
      Tempered: "Glass Side Panel",
    },
    image: "/products/case.jpg",
    inStock: true,
  },
  {
    id: "rtx-4080",
    name: "RTX 4080 Graphics Card",
    category: "GPUs",
    price: 1199,
    originalPrice: 1299,
    rating: 4.8,
    reviews: 389,
    description: "High-performance gaming GPU with 16GB GDDR6X memory",
    specs: {
      Memory: "16GB GDDR6X",
      Interface: "PCIe 4.0",
      Power: "320W",
      Architecture: "Ada Lovelace",
    },
    image: "/products/gpu2.jpg",
    inStock: true,
  },
  {
    id: "intel-i9-13900ks",
    name: "Intel Core i9-13900KS",
    category: "CPUs",
    price: 749,
    rating: 4.7,
    reviews: 267,
    description: "Latest flagship Intel processor with special edition clock speeds",
    specs: {
      Cores: "24 cores / 32 threads",
      "Base Clock": "3.4 GHz",
      "Boost Clock": "6.0 GHz",
      TDP: "150W",
    },
    image: "/products/cpu2.jpg",
    inStock: true,
  },
  {
    id: "phanteks-noctua",
    name: "Noctua NH-D15 CPU Cooler",
    category: "Cooling",
    price: 99,
    rating: 4.9,
    reviews: 412,
    description: "High-performance air cooler with excellent cooling capacity",
    specs: {
      Type: "Air Cooler",
      Fans: "2x 140mm",
      Height: "165mm",
      Socket: "LGA1700, AM5, AM4",
    },
    image: "/products/aircooler.jpg",
    inStock: true,
  },
  {
    id: "seagate-barracuda",
    name: "Seagate Barracuda Pro 4TB",
    category: "Storage",
    price: 149,
    rating: 4.5,
    reviews: 134,
    description: "7200 RPM HDD for backup and archival storage",
    specs: {
      Capacity: "4TB",
      Speed: "7200 RPM",
      Cache: "256MB",
      Interface: "SATA III",
    },
    image: "/products/hdd.jpg",
    inStock: true,
  },
  {
    id: "corsair-rgb-fans",
    name: "Corsair ML120 PRO RGB (3-Pack)",
    category: "Fans",
    price: 89,
    rating: 4.6,
    reviews: 201,
    description: "Magnetic levitation RGB fans with excellent static pressure",
    specs: {
      Size: "120mm",
      Count: "3 fans + Hub",
      "Max RPM": "2400 RPM",
      Lighting: "RGB with 16 LEDs",
    },
    image: "/products/fans.jpg",
    inStock: true,
  },
  {
    id: "cable-extensions",
    name: "Cablemod E-Series Pro Cables",
    category: "Cables",
    price: 79,
    rating: 4.7,
    reviews: 89,
    description: "Premium custom sleeved cables for clean builds",
    specs: {
      Material: "Premium Paracord",
      Compatibility: "Most EVGA/Corsair PSUs",
      Colors: "Multiple colors",
      Warranty: "Lifetime",
    },
    image: "/products/cables.jpg",
    inStock: true,
  },
];

export const CATEGORIES = [
  "All",
  "GPUs",
  "CPUs",
  "Memory",
  "Storage",
  "Power Supplies",
  "Cooling",
  "Motherboards",
  "Cases",
  "Fans",
  "Cables",
];

export const SORT_OPTIONS = [
  { value: "featured", label: "Featured" },
  { value: "price-low", label: "Price: Low to High" },
  { value: "price-high", label: "Price: High to Low" },
  { value: "rating", label: "Highest Rating" },
  { value: "newest", label: "Newest" },
];
